name: Update the commit id of parent repo
on:
  repository_dispatch:
    types:
      - submodule-updated
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Check out latest submodule
        run: |
          cd themes/next
          git fetch
          git checkout v7.8.0-swm
      - name: Push the latest submodule
        run: |
          cd ..
          git add .
          git commit -m "submodule updated"
          git push
